<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\tmgmt\Entity\RemoteMapping;
use Drupal\tmgmt_client\Plugin\tmgmt\Translator\ClientTranslator;
use Drupal\tmgmt\Entity\Job;
use Drupal\tmgmt\Entity\JobItem;

/**
 * Submit callback to pull translations form Gengo.
 */
function _tmgmt_client_pull_submit($form, FormStateInterface $form_state) {
  /**
   * @var Job $job
   */
  $job = $form_state->getFormObject()->getEntity();

  /**
   * @var ClientTranslator $translator
   */

  $controller = $job->getTranslator()->getPlugin();

  // Fetch everything for this job.
  $controller->pullRemoteItems($job);



  // drupal_set_message(t('All available translations from @server have been pulled.'), array('server' => $controller->));
}
