<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\tmgmt\Entity\RemoteMapping;
use Drupal\tmgmt_client\Plugin\tmgmt\Translator\ClientTranslator;
use Drupal\tmgmt\Entity\Job;
use Drupal\tmgmt\Entity\JobItem;

/**
 * Submit callback to pull translations form Gengo.
 */
function _tmgmt_client_pull_submit($form, FormStateInterface $form_state) {
  /**
   * @var Job $job
   */
  $job = $form_state->getFormObject()->getEntity();

  /**
   * @var ClientTranslator $translator
   */

  $translator = $job->getTranslator()->getPlugin();

  // Fetch everything for this job.
  $translator->pullRemoteItems($job);

  // Clear comments cache.
  // @todo: Improve cache id to clear cache for this job item only?
  \Drupal::cache('data')->delete('tmgmt_mygengo_comments_' . $job->id());

  // drupal_set_message(t('All available translations from @server have been pulled.'), array('server' => $controller->));
}
